#
# Module manifest for module 'SSH'
#
# Generated by: Carlos
#
# Generated on: 10/12/2012
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Posh-SSH.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '71e50ab0-4487-4fad-ab04-73cdf5d2dc7a'

# Author of this module
Author = 'VMware'

# Company or vendor of this module
CompanyName = 'VMware'

# Copyright statement for this module
Copyright = '(c) 2018-2020 VMware. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Module containing VMware.VimAutomation.Core types and methods for testing purposes.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

}